package com.groupa.week4laba.model;

import javax.persistence.*;

/******************************************************************************************
 * <p>The {@code User Model} contains all methods and variables required of a user object.
 * It includes username, an autogenerated ID, user level, and a total score.
 *</p>
 * @author Joshua Van Baalen (github.com/JoshuaJVB)
 * @version 0.1
 * @since   10-28-2020
 ******************************************************************************************/

@Entity
public class User {

    //properties

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long userId;
    @Column(unique = true)
    private String username;
    private Long totalScore;
    private Long level;

    //Constructors


    public User(){}

    public User(String username){
        this.username = username;
        totalScore = 0L;
        level = 1L;
    }

    //methods

    /****************************************************************
     * <p>sets total score for user, called after a match to add
     * score to totalScore</p>
     * @param num The new {@code totalScore} value
     ***************************************************************/

    public void setScore(Long num){
        totalScore += num;
        addLevel();
    }

    /*******************************************************************************
     * <p>increments level by one, called after a match to increase user level</p>
     ******************************************************************************/

    public void addLevel(){
        level++;
    }

    /************************
     * <p>returns userID</p>
     * @return userId
     ***********************/

    public Long getUserId() {
        return userId;
    }

    /**************************
     * <p>returns username</p>
     * @return username
     *************************/

    public String getUsername() {
        return username;
    }

    /*********************************************************
     * <p>Allows username to be initialized or changed</p>
     * @param username String to be used as username
     ********************************************************/

    public void setUsername(String username) {
        this.username = username;
    }

    /****************************
     * <p>returns total score</p>
     * @return totalScore value
     ***************************/

    public Long getTotalScore() {
        return totalScore;
    }

    /*********************************************
     * <p>overwrites total score value, used when
     * default constructor was used during
     * initialization</p>
     * @param totalScore the new totalScore value
     ********************************************/

    public void setTotalScore(Long totalScore) {
        this.totalScore = totalScore;
    }

    /************************************
     * <p>returns user's level</p>
     * @return level value
     ***********************************/

    public Long getLevel() {
        return level;
    }

    /********************************************
     * <p>overwrites level value, usually used
     * if user was created with empty constructor
     * </p>
     * @param level the new level value of user
     ********************************************/

    public void setLevel(Long level) {
        this.level = level;
    }
}
